# Setting for Source/Header files
set(SRCROOT "${ROOT_DIR}")
#file(GLOB SOURCE ${SRCROOT}/src/*.cpp)
#aux_source_directory(${SRCROOT}/src SOURCE)
file(GLOB dirs "${SRCROOT}/src/*")
foreach (item ${dirs})
	if(IS_DIRECTORY ${item})
		aux_source_directory(${item}/src SOURCE)
	endif ()
endforeach ()
aux_source_directory(${SRCROOT}/entry ENTRY)
include_directories(${SRCROOT}/include)
include_directories(${SRCROOT}/src)
