set(GOOGLE_LIBS_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/extlibs")
set(EXTLIBS)

set(_copy_dll OFF)
set(_find_gflags OFF)
set(_find_glog OFF)
set(_link_gflags OFF)
set(_link_glog OFF)

if (GFLAGS)
  set(_copy_dll ON)
  set(_find_gflags ON)
  set(_link_gflags ON)
endif ()
if (GLOG)
  set(_copy_dll ON)
  set(_find_gflags ON)
  set(_find_glog ON)
  set(_link_gflags OFF)
  set(_link_glog ON)
endif ()

if (_find_gflags)
  set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${GOOGLE_LIBS_ROOT}")
  add_definitions(-DENABLE_GFLAGS)
  find_package(gflags REQUIRED)
endif ()
if (_find_glog)
  set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} "${GOOGLE_LIBS_ROOT}/Lib/cmake/glog")
  add_definitions(-DENABLE_GLOG)
  find_package(glog REQUIRED)
endif ()
if (_link_gflags)
  set(EXTLIBS ${EXTLIBS} gflags)
endif ()
if (_link_glog)
  set(EXTLIBS ${EXTLIBS} glog::glog)
endif ()


if (MINGW AND _copy_dll)
  # Copy libstdc++-6.dll to binary dir
  string(REGEX REPLACE "^(.+/)[^/]+$" "\\1libstdc++-6.dll" LIBSTDCXX ${CMAKE_CXX_COMPILER})
  file(COPY ${LIBSTDCXX} DESTINATION ${CMAKE_BINARY_DIR})
endif ()

unset(_copy_dll)
unset(_find_gflags)
unset(_find_glog)
unset(_link_gflags)
unset(_link_glog)
